# Generated by Django 5.0.1 on 2026-01-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_page_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, default='Без названия', max_length=255),
        ),
    ]
