# Generated by Django 5.0.1 on 2026-01-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='format',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='page',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
