# Generated by Django 5.0.1 on 2026-01-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_block_format_page_is_public_page_share_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
